SED-1408 adapted row height and font size
exense/step-frontend pull request #170
Opened 2022-10-03 15:44 UTC by chillbirdo

2022-10-03 20:55 UTC, neogucky requested changes
Here we are changing the design for all tables to solve an edgecase. Let's just hide the lable for now until we can find a solution with our designer.

2022-10-05 18:22 UTC, chillbirdo commented
considered @dvladir comment in Jira

2022-10-05 22:00 UTC, neogucky commented on projects/step-core/src/lib/modules/table/components/table/table.component.scss
> +  }
This is still the incorrect row height

2022-10-05 22:02 UTC, neogucky requested changes
We still have to adjust the row height. Also I would prefer to use styles in legacy-styles to hide the error because:
- I don't like commented out code checked in
- We can't forget about these styles when we start working on 3.21 (since we will delete the legacy-styles first thing)

2022-10-10 13:01 UTC, closed without merging