SED-1463-Progress bar: increased opacity
exense/step-frontend pull request #210
Opened 2022-10-30 12:50 UTC by lucianbaciu

2022-10-31 08:33 UTC, dvladir submitted a review, later dismissed

2022-10-31 14:45 UTC, neogucky commented on projects/step-frontend/src/lib/modules/timeseries/performance-view/performance-view.component.html
> +    <div style="height: 12px; opacity: 0.2">
This should be performance-view.component.scss

2022-10-31 14:46 UTC, neogucky requested changes
Please move styles to the scss file

2022-11-01 09:59 UTC, neogucky approved these changes

2022-11-01 10:00 UTC, merged