Sed 1426 time range selection does not impact queries
exense/step-frontend pull request #232
Opened 2022-11-16 07:33 UTC by lucianbaciu

2022-11-16 07:49 UTC, dvladir approved these changes

2022-11-16 13:59 UTC, neogucky requested changes
Looks good but needs to be rabased on 3.21

2022-11-17 08:08 UTC, neogucky commented on projects/step-frontend/src/lib/modules/timeseries/performance-view/performance-view.config.ts
> +      mapFunction: (b: Bucket) => (b ? b.throughputPerHour / 60 / 60 : 0),
```suggestion
      mapFunction: (b: Bucket) => (b ? b.throughputPerHour / (60 * 60) : 0),
```

2022-11-17 08:10 UTC, neogucky approved these changes

2022-11-17 08:11 UTC, merged