SED-1568 redesign step tree view
exense/step-frontend pull request #268
Opened 2022-12-27 00:30 UTC by bojidaryovchev

2022-12-27 08:03 UTC, dvladir requested changes

2022-12-27 08:03 UTC, dvladir commented on projects/step-frontend/src/lib/modules/execution/components/execution-tree/execution-tree.component.scss
> +    --active-node-color: #5cb85c;
Should be set by scss variables, not css

2022-12-27 08:03 UTC, dvladir commented on projects/step-frontend/src/lib/modules/plan/components/plan-tree/plan-tree.component.scss
> +  --active-node-color: #0082cb;
Should be set by scss variables, not css

2022-12-27 08:03 UTC, dvladir commented on projects/step-core/src/lib/modules/tree/components/tree/tree.component.scss
> +    left: calc(var(--level) * 24px + var(--level) * 8px + 11px);
Here css variable is suitable, as it take value from angular's binding. Looks fine.

2022-12-27 15:13 UTC, dvladir submitted a review, later dismissed
@neogucky We need to deploy this branch, and check it visually

2022-12-28 07:45 UTC, neogucky commented
@dvladir https://stepos-sed-1568-redesign.exense.ch/#/root/plans/editor/63aacdcd6388605bb6d3beff

2022-12-28 07:48 UTC, neogucky approved these changes
I like the new look!

2022-12-28 08:06 UTC, dvladir approved these changes

2022-12-28 10:43 UTC, merged