SED-1544 migrate code editor
exense/step-frontend pull request #416
Opened 2023-04-14 13:34 UTC by dvladir

2023-04-14 14:34 UTC, neogucky requested changes
Looks good, but as far as I know there is no place that supports java editor in step. The keyword type script - java only supports uploaded JARs that are too complex to edit them just with the editor.

2023-04-14 16:49 UTC, bojidaryovchev commented on projects/step-frontend/src/lib/plugins-initializer/register-microfrontend-plugins.ts
> +  const modules = (await Promise.all(compileModules)).filter((x) => !!x) as CompiledModule[];
https://trello.com/c/p2rvxtAO/171-vs-boolean

2023-04-14 16:51 UTC, bojidaryovchev commented on projects/step-frontend/src/lib/plugins-initializer/register-microfrontend-plugins.ts
> +  const modules = (await Promise.all(compileModules)).filter((x) => !!x) as CompiledModule[];
I'd say for now either leave it as is or perhaps if you like Boolean() more you could use it instead, however I think this is something worth discussing and following everywhere

2023-04-14 16:52 UTC, bojidaryovchev commented on projects/step-frontend/src/lib/plugins-initializer/shared/module-utils.ts
> +  if (modulesWithInit.length > 0) {
> 0

2023-04-17 07:01 UTC, neogucky submitted a review, later dismissed

2023-04-17 07:59 UTC, bojidaryovchev approved these changes

2023-04-17 10:50 UTC, neogucky approved these changes

2023-04-17 12:07 UTC, merged