SED-2179 Restructured error handling for login page
exense/step-frontend pull request #514
Opened 2023-06-22 14:30 UTC by neogucky

2023-06-22 14:38 UTC, dvladir commented on projects/step-frontend/src/lib/modules/_common/interceptors/http-error.interceptor.ts
> +  public static handleError(error: any) {
```suggestion
  static formatError(error: any) {
```

2023-06-22 14:39 UTC, dvladir commented on projects/step-frontend/src/lib/modules/_common/interceptors/http-error.interceptor.ts
> +    }
```suggestion
    if (error.error?.errorMessage) {
      parsedError = HttpErrorInterceptor.formatError(error.error);
    } else if (error.name && error.message) {
      parsedError = HttpErrorInterceptor.formatError(`${error.name}: ${error.message}`);
    } else if (error.error) {
      parsedError = HttpErrorInterceptor.formatError(error.error);
    } else {
      parsedError = HttpErrorInterceptor.formatError('Unknown HTTP error');
    }
```

2023-06-22 14:41 UTC, dvladir requested changes
- Remove public modifier as redundant
- `handleError` is more about how the error object will be displayed as string now. I think it will be better to rename it.

2023-06-22 15:21 UTC, dvladir submitted a review, later dismissed

2023-06-23 10:01 UTC, bojidaryovchev submitted a review, later dismissed

2023-06-23 11:25 UTC, bojidaryovchev approved these changes

2023-06-26 16:33 UTC, merged