Sed 1059 tables artefactselecti
exense/step-frontend pull request #71
Opened 2022-07-20 16:13 UTC by chillbirdo

2022-07-21 08:16 UTC, dvladir commented on projects/step-frontend/src/lib/modules/plan/components/plan-artefact-list/plan-artefact-list.component.ts
> +    readonly _controllerApiService: AugmentedControllerService,
Can not find the usage of this service or it's datasource.
Is it required? If not I think both field and augmented service, can be removed

2022-07-21 08:21 UTC, dvladir requested changes
Seems `augmented-controller-service` isn't necessary. Can not find it's datasource usage.
If it so, I guess it can be removed

2022-07-21 08:36 UTC, chillbirdo commented
correct, I forgot to clean this up. I also removed all `public` modifiers ;)

2022-07-21 08:45 UTC, dvladir submitted a review, later dismissed

2022-07-26 13:59 UTC, neogucky commented
@chillbirdo can you do the merge? It looks like there are differences between the implementation here and in  "Sed 1054 tables functionselecti"

2022-07-26 14:00 UTC, neogucky submitted a review, later dismissed

2022-07-27 03:01 UTC, chillbirdo commented
done, ready to be merged!

2022-08-04 07:58 UTC, neogucky approved these changes
looks good!

2022-08-04 07:58 UTC, merged