Sed 2750 timeseries   more button shows already existing filters
exense/step-frontend pull request #736
Opened 2024-02-21 13:18 UTC by lucianbaciu

2024-02-22 14:49 UTC, dvladir requested changes

2024-02-22 14:49 UTC, dvladir commented on projects/step-frontend/src/lib/modules/timeseries/components/dashboard/dashboard.component.ts
> +    let newDashlet: DashboardItem = {
```suggestion
    const newDashlet: DashboardItem = {
```

2024-02-22 14:49 UTC, dvladir commented on projects/step-frontend/src/lib/modules/timeseries/modules/filter-bar/components/dashboard-filter-bar/dashboard-filter-bar.component.ts
> +  };
Where is it used?

2024-02-29 08:44 UTC, lucianbaciu commented on projects/step-frontend/src/lib/modules/timeseries/modules/filter-bar/components/dashboard-filter-bar/dashboard-filter-bar.component.ts
> +    this.context.onAttributesChange().subscribe((attributes: Record<string, MetricAttribute>) => {
yes, good catch

2024-02-29 10:51 UTC, lucianbaciu commented
@neogucky please check

2024-02-29 10:55 UTC, dvladir approved these changes

2024-03-01 14:26 UTC, neogucky approved these changes

2024-03-06 15:31 UTC, merged