SED-1143: Rework tables API (FE)
exense/step-frontend pull request #74
Opened 2022-07-26 15:03 UTC by dvladir

2022-08-04 07:55 UTC, neogucky commented on projects/step-core/src/lib/modules/table/shared/table-remote-data-source.ts
> +  // }
@dvladir this can no be done like this, I had not had time to update the code, can you quickly add this?

 {"oql":"not(resourceType=attachment)"}

2022-08-04 07:56 UTC, neogucky requested changes
Looks good to me! I added the open point but it is defenitely a nice improvement

2022-08-08 10:43 UTC, chillbirdo submitted a review, later dismissed
Looks good to me. I only rechecked it now, since I reviewed it once before I went to vacation but did not approve because it was/is still a draft.

2022-08-11 06:34 UTC, neogucky approved these changes
Looks good to me and also the oql filters looked correct in https://stepos-sed-987-new-table-api.exense.ch/#/root/resources

2022-08-11 14:31 UTC, neogucky approved these changes

2022-08-11 14:31 UTC, merged