SED-3029 make input take whole space
exense/step-frontend pull request #805
Opened 2024-04-17 10:50 UTC by lukasz-lepa

https://exense.atlassian.net/browse/SED-3029

2024-04-17 11:50 UTC, dvladir requested changes

2024-04-17 11:50 UTC, dvladir commented on projects/step-core/src/lib/modules/custom-forms/components/custom-form/custom-form.component.scss
> +  }
- It make sense for inline forms only.
- Avoid class names, that duplicates style rules

```suggestion
  .inline.fill-whole-space {
    flex: 1;
  }
```

2024-04-19 08:30 UTC, neogucky submitted a review, later dismissed

2024-04-19 09:07 UTC, dvladir submitted a review, later dismissed

2024-04-30 13:21 UTC, neogucky approved these changes

2024-04-30 13:21 UTC, merged