Sed 2964 compare mode for custom dashboards
exense/step-frontend pull request #815
Opened 2024-05-02 14:59 UTC by lucianbaciu

2024-05-03 10:23 UTC, neogucky requested changes

2024-05-03 12:13 UTC, lucianbaciu commented on projects/step-core/src/lib/client/generated/models/AxesSettings.ts
> +  colorizationType?: 'STROKE' | 'FILL';
@neogucky you are right. it was defined with a default value but forgot the @NotNull annotation. will add it back

2024-05-03 12:32 UTC, lucianbaciu commented on projects/step-frontend/src/lib/modules/timeseries/components/table-dashlet/table-dashlet.component.ts
> +    }
good point. y being 0 is a good scenario

2024-05-06 07:01 UTC, neogucky commented on projects/step-frontend/src/lib/modules/timeseries/components/chart-dashlet/chart-dashlet.component.ts
> +    console.log('LOCK STATE');
```suggestion
```

2024-05-06 07:02 UTC, neogucky approved these changes
Please remove the remaining logs, afterwards a merge would be fine from my side

2024-05-07 14:05 UTC, neogucky approved these changes

2024-05-07 14:06 UTC, merged