SED-3174 dropdown filter
exense/step-frontend pull request #866
Opened 2024-06-11 10:11 UTC by neogucky

2024-07-11 11:04 UTC, dvladir requested changes

2024-07-11 11:04 UTC, dvladir commented on projects/step-core/src/lib/modules/plan-common/components/plan-create-dialog/plan-create-dialog.component.ts
> +  }
Observable created in the subscription of another observable.
It's not clear when `dropdownItemsTypeFilter$` will be destroyed.
Please organize it in a single observable chain (Check the commend above).
Also in current case the `combineLatest` will be required.

2024-07-11 11:04 UTC, dvladir commented on projects/step-frontend/src/lib/modules/function/components/function-configuration-dialog/function-configuration-dialog.component.html
> +          <mat-option *ngFor="let itemInfo of dropdownItemsFiltered" [value]="itemInfo.type">
@for

2024-07-17 09:48 UTC, lukasz-lepa commented on projects/step-core/src/lib/modules/basics/components/array-filter/array-filter.component.ts
> +  }
All good, but I don't think debounceTime is necessary here

2024-07-22 14:47 UTC, merged