SED-3521 show helpful info if no plans exist
exense/step-frontend pull request #971
Opened 2024-10-24 10:32 UTC by AmirBenkoula

2024-10-24 19:26 UTC, neogucky commented on projects/step-core/src/lib/modules/table/components/table/table.component.ts
> +    });
```suggestion
    this._router.navigate(['functions','configure', 'new']);
```

2024-10-24 19:26 UTC, neogucky commented on projects/step-core/src/lib/modules/table/components/table/table.component.html
> +        </p>
```suggestion
        <h3>3. Execute Plan</h3>
        <p>
          After creating and combining Keywords in a Plan, you can execute it. Next steps include setting up scheduled executions and monitoring as required.
        </p>
```

2024-10-24 19:26 UTC, neogucky commented on projects/step-core/src/lib/modules/table/components/table/table.component.html
> +          Open Documentation
```suggestion
         Documentation
```

2024-10-24 19:26 UTC, neogucky commented on projects/step-core/src/lib/modules/table/components/table/table.component.html
> +          (click)="openUrl('https://step.dev/knowledgebase/userdocs/schedulerview/')"
```suggestion
          (click)="openUrl('https://step.dev/knowledgebase/userdocs/executions/')"
```

2024-10-24 19:26 UTC, neogucky commented on projects/step-core/src/lib/modules/table/components/table/table.component.html
> +        </button>
```suggestion
```

2024-10-24 19:26 UTC, neogucky commented on projects/step-core/src/lib/modules/table/components/table/table.component.ts
> +    });
```suggestion
    this._router.navigate(['functions', 'configure', 'new']);
```

2024-10-24 19:26 UTC, neogucky commented on projects/step-core/src/lib/modules/table/components/table/table.component.ts
> +  }
```suggestion
```

2024-10-30 08:26 UTC, dvladir requested changes
Table is a core reusable component, which is widely used across the application. (And not only in main views)
It shouldn't contain any information that doesn't relate to table's functionality.

Instead of hard-coding quick action panels inside the table - it should be implemented as separate component and inserted in table with specific ng-content.

Then this quick action panel should be applied only to those views, where it's really required.

2025-02-21 10:30 UTC, closed without merging